#!/bin/bash
#Program
#User input a filename,program will check the flowing:
#1.)exist? 2.)file/directory? 3.)file permissions
#History:
#2019/05/31 Zomkey First release
PATH=/bin:/sbin:/usr/bin:/usr/sbin:/usr/local/bin:/usr/local/sbin:~/bin
export PATH
#使用者输入档名，判断是否有输入字符
echo -e "Please input a filename,I will check the filename's type and permission. \n\n"
read -p "Input a filename:" filename
test -z #{filename} && echo "You must input a filename." && exit 0
#判断档案是否存在，不存在则显示讯息并结束脚本
test ! -e ${filename} && echo " The filename '${filename}' DO NOT exist" && exit 0
#判断档案的类型和属性
test -f ${filename} && filetype="regulare file"
test -d ${filename} && filetype="directory"
test -r ${filename} && perm="readable"
test -w ${filename} && perm="${perm} writable"
test -x ${filename} && perm="${perm} executable"
#输出信息
echo "The filename: ${filename} is a ${filetype}"
echo "And its permission is :${perm}"
