#!/bin/bash
#Program:
#Show "Heloo" from $1... by using case...esac
#History:
#2019/06/02 Zomkey First release
PATH=/bin:/sbin:/usr/bin:/usr/sbin:/usr/local/bin:/usr/local/sbin:~/bin
export PATH
case ${1} in
"hello")
	echo "Hello,how are you?"
	;;
"")
	echo "You must input parameters.ex => someword}"
	;;
*)
	echo " Usage ${0} {hello}"
	;;
esac
