#!/bin/bash
#Program:
#User input 2 integer numbers,then program will cross these two numbers.
#History:
#2019/05/30 Zomkey First release
PATH=/bin:/sbin:/usr/bin:/usr/sbin:/usr/local/bin:/usr/local/sbin:~/bin
export PATH
echo -e "Your should input 2 numbers,I will multiplying them! \n "
#read -p 'fisrt number: ' firstnu
#read -p 'second number: ' secnu
read -p "first number: " firstnu 
read -p "second number: " secnu
total=$((${firstnu}*${secnu})) 
echo -e "\nThe result of ${firstnu} x ${secnu} is ==> ${total}"
