#!/bin/bash
#Program:
#This script only accepts the flowing parameters:one,two,three.
#History:
#2019/06/02 Zomkey First release
PATH=/bin:/sbin:/usr/bin:/usr/sbin:/usr/local/bin:/usr/local/sbin:~/bin
export PATH
echo "This program will print your selection!"
read -p "Input your choice:" choice
case ${choice} in 
#case ${1} in
"one")
	echo "Your choice is one"
	;; 
"two")
	echo "Your choice is two"
	;; 
"three")
	echo "Your choice is three"
	;; 
*)
	echo "Usage ${0} {one|two|three}"
	;; 
esac
