#!/bin/bash
# Program:
#Use function to repeat information.
#History:
#2019/06/02	Zomkey	First release
PATH=/bin:/sbin:/usr/bin:/usr/sbin:/usr/local/bin:/usr/local/sbin:~/bin
export PATH
function printit(){
	echo "Your choice is ${1}"   #  $1 要参考底下指令
}

echo "This program will print your selection !"
case ${1} in
"one")
	printit One  # 注意， printit 指令后面接参数
	;;
"two")
	printit Two
	;;
"three")
  	printit Three
	;;
*)
  	echo "Usage ${0} {one|two|three}"
	;;
esac
